services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    environment:
      - REACT_APP_API_URL=${SERVICE_URL_BACKEND}
      - VITE_API_BASE_URL=${SERVICE_URL_BACKEND}
      - PORT=3000
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - SEARXNG_BASE_URL=http://searxng:8080
      - REDIS_URL=redis://redis:6379
      - PORT=7777
      - BACKEND_PORT=7777
      - PYTHONPATH=/app
      - WORK_DIR=/opt/workspace
    volumes:
      - workspace_data:/opt/workspace
    depends_on:
      - redis
      - searxng

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  searxng:
    image: searxng/searxng:latest
    environment:
      - SEARXNG_SECRET=${SEARXNG_SECRET:-mysecretkey}
    volumes:
      - searxng_config:/etc/searxng

volumes:
  workspace_data:
  redis_data:
  searxng_config:
