version: '3.8'

services:
  backend:
    build: .
    ports:
      - "7777:8000"
    environment:
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
    command: ["python3", "api.py"]

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8000
    depends_on:
      - backend

  redis:
    image: redis:7-alpine
    restart: unless-stopped

  searxng:
    image: searxng/searxng:latest
    restart: unless-stopped
