version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3001:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:7777
    depends_on:
      - backend
    networks:
      - agenticseek-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "7777:7777"
    environment:
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - SEARXNG_BASE_URL=http://searxng:8081
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
      - searxng
    networks:
      - agenticseek-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - agenticseek-network

  searxng:
    image: searxng/searxng:latest
    ports:
      - "8081:8080"
    environment:
      - SEARXNG_SECRET=${SEARXNG_SECRET:-mysecretkey}
    networks:
      - agenticseek-network

networks:
  agenticseek-network:
    driver: bridge
