version: '3.8'

services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - agenticseek-network

  searxng:
    image: searxng/searxng:latest
    restart: unless-stopped
    ports:
      - "8081:8080"  # Changed from 8080 to 8081 to avoid conflict
    volumes:
      - ./searxng/settings.yml:/etc/searxng/settings.yml:ro
      - ./searxng/limiter.toml:/etc/searxng/limiter.toml:ro
    environment:
      - SEARXNG_BASE_URL=https://${SEARXNG_HOSTNAME:-localhost:8081}/
    networks:
      - agenticseek-network
    depends_on:
      - redis

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: unless-stopped
    ports:
      - "8000:8000"  # Backend runs on port 8000
    environment:
      - SEARXNG_BASE_URL=http://searxng:8080
      - REDIS_URL=redis://redis:6379
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY:-}
      - TOGETHER_API_KEY=${TOGETHER_API_KEY:-}
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-}
    volumes:
      - models:/app/models
      - hf-cache:/root/.cache/huggingface
    networks:
      - agenticseek-network
    depends_on:
      - redis
      - searxng

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=${SERVICE_URL_BACKEND}
    networks:
      - agenticseek-network
    depends_on:
      - backend

volumes:
  redis_data:
  models:
  hf-cache:

networks:
  agenticseek-network:
    driver: bridge
