version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3001:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:7777
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "7777:7777"  # Changed from 8000 to 7777
    environment:
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - SEARXNG_BASE_URL=http://searxng:8081
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
      - searxng
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  searxng:
    image: searxng/searxng:latest
    ports:
      - "8081:8080"
    restart: unless-stopped
