version: '3.8'

services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  searxng:
    image: searxng/searxng:latest
    restart: unless-stopped
    ports:
      - "8081:8080"
    volumes:
      - ./searxng:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=https://${SEARXNG_HOSTNAME:-localhost}/
    depends_on:
      - redis

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - SEARXNG_BASE_URL=http://searxng:8080
      - REDIS_URL=redis://redis:6379
      - API_URL=${API_URL:-http://localhost:8000}
      - WORKSPACE_DIR=/opt/workspace
    volumes:
      - workspace_data:/opt/workspace
      - /tmp:/tmp
    depends_on:
      - redis
      - searxng
    command: ["python", "-m", "uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}
      - BACKEND_URL=${BACKEND_URL}
      - HOST=0.0.0.0
      - PORT=3000
    depends_on:
      - backend
    command: ["npm", "start"]

volumes:
  redis_data:
  workspace_data:
