version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    environment:
      - SERVICE_FQDN_FRONTEND_3000
      - REACT_APP_BACKEND_URL=${SERVICE_URL_BACKEND}
      - VITE_API_BASE_URL=${SERVICE_URL_BACKEND}
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - SERVICE_FQDN_BACKEND_8000
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - SEARXNG_BASE_URL=http://searxng:8080
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
      - searxng
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    restart: unless-stopped

  searxng:
    image: searxng/searxng:latest
    environment:
      - SEARXNG_SECRET=${SEARXNG_SECRET:-mysecretkey}
    restart: unless-stopped
