services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE_URL=${BACKEND_URL:-http://backend:8000}
    depends_on:
      - backend
    networks:
      - agenticseek-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - SEARXNG_BASE_URL=http://searxng:8080
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
      - searxng
    networks:
      - agenticseek-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - agenticseek-network

  searxng:
    image: searxng/searxng:latest
    ports:
      - "8080:8080"
    environment:
      - SEARXNG_SECRET_KEY=${SEARXNG_SECRET_KEY:-your-secret-key-here}
    networks:
      - agenticseek-network

networks:
  agenticseek-network:
    driver: bridge
