version: '3.8'

services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped

  searxng:
    image: searxng/searxng:latest
    restart: unless-stopped
    expose:
      - "8080"
    volumes:
      - ./searxng/settings.yml:/etc/searxng/settings.yml:ro
      - ./searxng/uwsgi.ini:/etc/searxng/uwsgi.ini:ro
      - ./searxng/limiter.toml:/etc/searxng/limiter.toml:ro
    environment:
      - SEARXNG_BASE_URL=${SERVICE_URL_SEARXNG:-http://localhost:8080/}

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: unless-stopped
    expose:
      - "8000"
    environment:
      - SEARXNG_BASE_URL=http://searxng:8080
      - REDIS_URL=redis://redis:6379
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
    depends_on:
      - redis
      - searxng

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    restart: unless-stopped
    expose:
      - "3000"
    environment:
      - REACT_APP_BACKEND_URL=${SERVICE_URL_BACKEND}
      - PORT=3000
      - HOST=0.0.0.0
    depends_on:
      - backend
