version: '3.8'

services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - agenticseek_network

  searxng:
    image: searxng/searxng:latest
    restart: unless-stopped
    ports:
      - "8081:8080"  # Changed from 8080 to 8081
    volumes:
      - ./searxng:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=https://${SEARXNG_HOSTNAME:-localhost:8081}/
    networks:
      - agenticseek_network
    depends_on:
      - redis

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: unless-stopped
    ports:
      - "8000:8000"  # Backend runs on 8000
    environment:
      - SEARXNG_BASE_URL=http://searxng:8080
      - REDIS_URL=redis://redis:6379
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY:-}
      - GROQ_API_KEY=${GROQ_API_KEY:-}
      - TOGETHER_API_KEY=${TOGETHER_API_KEY:-}
      - XAI_API_KEY=${XAI_API_KEY:-}
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-}
      - SERPAPI_API_KEY=${SERPAPI_API_KEY:-}
      - BRAVE_SEARCH_API_KEY=${BRAVE_SEARCH_API_KEY:-}
      - FLIGHT_API_KEY=${FLIGHT_API_KEY:-}
      - SPEECH_MODEL=${SPEECH_MODEL:-kokoro}
      - SPEECH_ENABLED=${SPEECH_ENABLED:-false}
      - HEADLESS=${HEADLESS:-true}
    volumes:
      - ./sources:/app/sources
      - ./prompts:/app/prompts
      - ./llm_router:/app/llm_router
    networks:
      - agenticseek_network
    depends_on:
      - redis
      - searxng

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    restart: unless-stopped
    ports:
      - "3001:3000"  # Changed from 3000 to 3001
    environment:
      - REACT_APP_BACKEND_URL=${SERVICE_URL_BACKEND}
      - NODE_ENV=production
    networks:
      - agenticseek_network
    depends_on:
      - backend

volumes:
  redis_data:

networks:
  agenticseek_network:
    driver: bridge
