services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    environment:
      - REACT_APP_BACKEND_URL=${SERVICE_URL_BACKEND}
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - SEARXNG_BASE_URL=http://searxng:8080
      - REDIS_URL=redis://redis:6379
      - PORT=8000
    depends_on:
      - redis
      - searxng

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes

  searxng:
    image: searxng/searxng:latest
    environment:
      - SEARXNG_SECRET=${SEARXNG_SECRET:-mysecretkey}
