version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - WORK_DIR=/opt/workspace
      - REDIS_URL=redis://redis:6379
      - SEARXNG_BASE_URL=http://searxng:8080/
    env_file:
      - .env
    depends_on:
      - redis
      - searxng
    volumes:
      - ./hf_cache:/root/.cache/huggingface
      - ./models:/opt/workspace/models
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - REACT_APP_BACKEND_URL=${SERVICE_URL_BACKEND:-http://localhost:8000}
    depends_on:
      - backend
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  searxng:
    image: searxng/searxng:latest
    ports:
      - "8080:8080"
    environment:
      - SEARXNG_SECRET=${SEARXNG_SECRET:-6baef84cc83608c854f78dfd35a58b90d1c63e95c9a38a09969c113f56445c0d}
    volumes:
      - ./searxng/settings.yml:/etc/searxng/settings.yml:ro
      - ./searxng/limiter.toml:/etc/searxng/limiter.toml:ro
    restart: unless-stopped

volumes:
  redis_data:
