version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - SEARXNG_BASE_URL=http://searxng:8080
      - REDIS_BASE_URL=redis://redis:6379/0
      - WORK_DIR=/app/workspace
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY:-}
    volumes:
      - ./workspace:/app/workspace
    depends_on:
      - redis
      - searxng
    command: ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    networks:
      - agenticseek-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=${SERVICE_URL_BACKEND:-http://localhost:8000}
    depends_on:
      - backend
    networks:
      - agenticseek-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - agenticseek-network

  searxng:
    image: searxng/searxng:latest
    ports:
      - "8080:8080"
    environment:
      - SEARXNG_BASE_URL=http://searxng:8080
    networks:
      - agenticseek-network

networks:
  agenticseek-network:
    driver: bridge
